version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: APISELETIVO
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
      - minio
    ports:
      - "8181:8181"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=36856101
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=meu-bucket
      - AWS_ENDPOINT=http://minio:9000

  db:
    image: postgres:latest
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: laravel_minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Painel Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
